version: 3.0.1.{build}
branches:
  only:
  - master
image: Visual Studio 2022
environment:
  $msbuildPath: $(cmd /c where msbuild)
  COVERALLS_REPO_TOKEN: hgIQF4YzTnoNUn5KyS9onk6vbbjaGLWrN

configuration: Release

build_script:
  - ps: .\build.ps1 -Target CiBuild -Experimental
  
test_script:
  - cmd: dotnet test ./BoletoNetCore.Testes

artifacts:
  - path: '**\boleto*.nupkg'
    name: nuget

deploy:
- provider: NuGet
  server: https://www.myget.org/F/boletonetcorebuild/
  api_key:
    secure: rH9VFKFXJsR5D07BF9PayFm7mRo7acVANtfgYkGa3S9ybX0RCWBiSM153yhLaorG
  skip_symbols: true
  on:
    branch: master
    
notifications:
- provider: Email
  to:
  - cds@cds-software.com.br
  subject: BoletoNetCore Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
